Repository decentraland/places, pull requests merged in 2022-11, with the labels that each got.

#140 chore: update decentraland-gatsby
  package-lock.json
  package.json
  src/components/Place/PlaceList/PlaceList.css
  src/components/Place/PlaceList/PlaceList.tsx
Labels: bug, enhancement

#141 Feat: replaces place images with static ones
  src/entities/Place/migration.ts
  src/entities/Place/utils.ts
  src/migrations/1667326512314_add-update-static-places.ts
  src/seed/02_places.json
  src/seed/index.test.ts
  static/images/places/.gitkeep
  static/images/places/butterfly_prawn.jpeg
  static/images/places/ice_poker_the_stronghold.jpeg
  static/images/places/wondermine.jpeg
Labels: enhancement

#142 fix: import in migration
  src/entities/Place/migration.ts
Labels: bug

#144 Feat: steps to migrate
  bin/placeMigrations.ts
  package.json
  src/seed/index.test.example
  src/seed/migration.ts.example
  src/seed/places.json.example
Labels: enhancement

#145 Feat: add new places and edit old one
  bin/placeMigrations.ts
  src/migrations/1667407333574_automatic-update-static-places
  src/seed/03_places.json
  src/seed/index.test.ts
  static/images/places/dice_masters.jpeg
Labels: enhancement

#146 Feat: add fixed pois
  bin/placeMigrations.ts
  src/components/Place/PlaceCard/PlaceCard.css
  src/components/Place/PlaceCard/PlaceCard.tsx
  src/hooks/usePlaceListPois.ts
  src/intl/en.json
  src/migrations/1667407333574_automatic-update-static-places.ts
  src/pages/index.tsx
Labels: bug, enhancement

#148 Fix: hide pagination with no places
  src/components/Layout/OverviewList.css
  src/components/Place/PlaceCard/PlaceCard.tsx
  src/components/Place/PlaceDescription/PlaceDescription.css
  src/components/Place/PlaceFeatured/PlaceFeatured.css
  src/components/Place/PlaceFeatured/PlaceFeatured.tsx
  src/components/Place/PlaceList/PlaceList.css
  src/components/Place/PlaceStats/PlaceStats.css
  src/intl/en.json
  src/modules/segment.ts
  src/pages/index.css
  src/pages/my_places.tsx
  src/pages/places.css
  src/pages/places.tsx
Labels: bug

#149 Feat: add property featured image
  src/components/Place/PlaceFeatured/PlaceFeatured.tsx
  src/entities/Place/types.ts
  src/migrations/1667567288297_add-featured-image.ts
  src/seed/places.json.example
Labels: enhancement

#151 feat: new card style
  src/components/Icon/Preview.css
  src/components/Icon/Preview.tsx
  src/components/Label/UserPreviewCount/UserPreviewCount.css
  src/components/Label/UserPreviewCount/UserPreviewCount.tsx
  src/components/Place/PlaceCard/PlaceCard.css
  src/components/Place/PlaceCard/PlaceCard.tsx
  src/components/Place/PlaceDetails/PlaceDetails.tsx
Labels: enhancement

#152 style: issue with PlaceCard devider
  src/components/Place/PlaceCard/PlaceCard.css
Labels: bug

#156 Fix: card sizes without owner
  src/components/Place/PlaceCard/PlaceCard.css
  src/migrations/1667826308625_automatic-update-static-places.ts
  src/pages/index.tsx
  src/seed/04_places.json
  src/seed/index.test.ts
Labels: bug, enhancement

#159 style: add ellipsis to creator in PlaceCard
  src/components/Place/PlaceCard/PlaceCard.css
Labels: enhancement

#163 feat: add new places
  src/migrations/1668011471669_automatic-update-static-places.ts
  src/seed/06_places.json
  src/seed/index.test.ts
Labels: enhancement

#166 fix: change images from last migration
  src/migrations/1668189003142_automatic-update-static-places.ts
  src/seed/08_places.json
  src/seed/index.test.ts
Labels: bug

#167 fix: wrong image showing in highlighted places
  src/components/Place/PlaceFeatured/PlaceFeatured.tsx
  src/migrations/1668191619253_automatic-update-static-places.ts
  src/modules/segment.ts
  src/seed/09_places.json
  src/seed/index.test.ts
Labels: bug

#169 feat: add places to Navbar
  gatsby-browser.js
  package-lock.json
  package.json
Labels: enhancement

#175 feat: add image to DragonCity
  src/migrations/1668694049337_automatic-update-static-places.ts
  src/seed/10_places.json
  src/seed/index.test.ts
  src/seed/places.json.example
  static/images/places/dragon-city.png
Labels: enhancement

#176 feat: Place stats: added and updated
  src/__data__/entities.ts
  src/api/DataTeam.ts
  src/components/Place/PlaceStats/PlaceStats.tsx
  src/entities/Place/model.ts
  src/entities/Place/routes/getPlace.test.ts
  src/entities/Place/routes/getPlace.ts
  src/entities/Place/routes/getPlaceList.test.ts
  src/entities/Place/routes/getPlaceList.ts
  src/entities/Place/routes/getPlaceMostActiveList.ts
  src/entities/Place/routes/getPlaceUserVisitsList.ts
  src/entities/Place/schemas.ts
  src/entities/Place/types.ts
  src/entities/Place/utils.ts
  src/intl/en.json
  src/modules/entityScene.ts
  src/modules/locations.ts
  src/pages/index.tsx
  src/pages/places.tsx
Labels: enhancement

#177 Feat: change route in place from id to position
  package-lock.json
  package.json
  src/components/Place/PlaceCard/PlaceCard.tsx
  src/components/Place/PlaceDescription/PlaceDescription.tsx
  src/components/Place/PlaceDetails/PlaceDetails.tsx
  src/components/Place/PlaceFeatured/PlaceFeatured.tsx
  src/components/Place/PlaceRealmActivity/PlaceRealmActivity.tsx
  src/components/Place/PlaceStats/PlaceStats.tsx
  src/entities/Place/utils.ts
  src/entities/Social/routes.ts
  src/hooks/usePlaceFromParams.ts
  src/hooks/usePlaceId.ts
  src/hooks/usePlacesManager.ts
  src/modules/locations.ts
  src/pages/place.tsx
  src/theme.css
  src/utils/position/toCanonicalPosition.test.ts
  src/utils/position/toCanonicalPosition.ts
Labels: bug, enhancement

#180 chore: update decentraland-gatsby 5.49.1
  package-lock.json
  package.json
Labels: bug

#182 feat: add api docs
  gatsby-browser.js
  package-lock.json
  package.json
  src/components/Layout/UserMenu.tsx
  src/intl/en.json
  src/modules/locations.ts
  src/pages/docs.tsx
Labels: enhancement

#184 feat: adding new places and updating golfcraft
  src/migrations/1669376178912_automatic-update-static-places.ts
  src/seed/11_places.json
  src/seed/index.test.ts
Labels: enhancement

#186 fix: type in track filter change
  src/entities/Place/migration.ts
  src/pages/my_places.tsx
  src/pages/places.tsx
Labels: bug
