Repository decentraland/places, pull requests merged in 2023-04, with the labels that each got.

#238 feat: removing fashion week features and replacing with new ones
  src/migrations/1680712434879_automatic-update-static-places.ts
  src/seed/30_places.json
  src/seed/index.test.ts
Labels: enhancement

#240 feat: change like_rate default value to 0
  src/migrations/1680794073381_change-like-rate-default.ts
Labels: stream-discoverability

#223 Feat: create task to get scene data from catalyst
  README.md
  bin/filesToSqs.ts
  bin/placeMigrations.ts
  bin/snapshotToFiles.ts
  package-lock.json
  package.json
  src/__data__/entities.ts
  src/api/DataTeam.test.ts
  src/api/DataTeam.ts
  src/components/Place/PlaceStats/PlaceStats.tsx
  src/entities/Category/model.test.ts
  src/entities/CheckScenes/data/roads.json
  src/entities/CheckScenes/model.ts
  src/entities/CheckScenes/task/checkScenes.ts
  src/entities/CheckScenes/task/consumer.ts
  src/entities/CheckScenes/task/processContentEntityScene.test.ts
  src/entities/CheckScenes/task/processContentEntityScene.ts
  src/entities/CheckScenes/task/processEntityId.test.ts
  src/entities/CheckScenes/task/processEntityId.ts
  src/entities/CheckScenes/task/taskRunnerSqs.ts
  src/entities/CheckScenes/types.ts
  src/entities/CheckScenes/utils.test.ts
  src/entities/CheckScenes/utils.ts
  src/entities/DeploymentTrack/types.ts
  src/entities/DeploymentTrack/utils.ts
  src/entities/Place/migration.test.ts
  src/entities/Place/migration.ts
  src/entities/Place/model.test.ts
  src/entities/Place/model.ts
  src/entities/Place/routes/getPlace.test.ts
  src/entities/Place/routes/getPlace.ts
  src/entities/Place/routes/getPlaceList.test.ts
  src/entities/Place/routes/getPlaceList.ts
  src/entities/Place/routes/getPlaceMostActiveList.ts
  src/entities/Place/routes/getPlaceUserVisitsList.ts
  src/entities/Place/schemas.ts
  src/entities/Place/types.ts
  src/entities/Place/utils.test.ts
  src/entities/Place/utils.ts
  src/entities/Slack/utils.ts
  src/entities/UserLikes/model.test.ts
  src/entities/UserLikes/model.ts
  src/entities/UserLikes/schema.ts
  src/migrations/1677772556705_add-visible-to-places.ts
  src/migrations/1679517269016_add-worlds-properties.ts
  src/migrations/1681243168803_add-deployed-at.ts
  src/migrations/1681919300479_add-table-to-store-sqs-queue-logs.ts
  src/modules/entityScene.ts
  src/modules/hotScenes.ts
  src/pages/docs.tsx
  src/pages/index.tsx
  src/seed/indexNew.test.example
  src/seed/migration.ts.example
  src/seed/places.json.example
  src/server.ts
  src/utils/array/areSamePositions.test.ts
  src/utils/array/areSamePositions.ts
  src/utils/array/areShrinkPositions.test.ts
  src/utils/array/areShrinkPositions.ts
Labels: stream-discoverability

#244 fix: migrations order
  src/migrations/1677772556705_add-visible-to-places.ts
  src/migrations/1681243168802_add-worlds-properties.ts
  src/migrations/1681243168803_add-deployed-at.ts
Labels: bug, stream-discoverability
